### ISSUE TITLE
Add onTapDown on backdrop

### ISSUE THREAD

**Issue by mano290** [akshathjain/sliding_up_panel#70] opened 2019-10-30 03:22 UTC
Hello guys,

Would it be possible to put the `onTapDown` event in the backdrop?
Using the same function already created? `_close()`
```
//the backdrop to overlay on the body
!widget.backdropEnabled ? Container() : GestureDetector(
  onTap: widget.backdropTapClosesPanel ? _close : null,
  // Event when user drag down
  onTapDown: widget.backdropTapClosesPanel ? (details) => _close() : null,
  child: Opacity(
     opacity: _ac.value * widget.backdropOpacity,
     child: Container(
       height: MediaQuery.of(context).size.height,
       width: MediaQuery.of(context).size.width,
           
       //set color to null so that touch events pass through
       //to the body when the panel is closed, otherwise,
       //if a color exists, then touch events won't go through
       color: _ac.value == 0.0 ? null : widget.backdropColor,
     ),
   ),
),
```

**Comment by akshathjain** [comment] 2019-12-26 20:02
This is a duplicate of #24, which was closed some time ago. Please refer to that issue for more information about this. Although since this is the second request for this feature, I might add it in the future if more people would like to see it. Closing the issue for now.

**Closed by akshathjain** 2019-12-26 20:02 UTC
