### ISSUE TITLE
Scrollable content as body

### ISSUE THREAD

**Issue by jld3103** [akshathjain/sliding_up_panel#43] opened 2019-07-20 15:48 UTC
How can I add something scrollable like a ListView as the body?
Currently the closed panel hides the content and disables scrolling on the content.
Also a padding beneath the closed panel needs to be added for that.
Is such thing possible yet?

**Comment by akshathjain** [comment] 2019-08-01 16:18
Duplicate of #17

**Comment by jld3103** [comment] 2019-08-02 15:22
@akshathjain It's not the same issue. I ended up using a simple Stack.

**Comment by akshathjain** [comment] 2019-08-02 16:37
My bad, I misinterpreted your question.

**Comment by jld3103** [comment] 2019-08-02 20:56
Maybe my implementation could be merged in the package? It's very simple

**Comment by phillippbertram** [comment] 2019-08-30 06:44
@jld3103 could you possibly provide your solution? 🙃

**Comment by jld3103** [comment] 2019-08-30 20:25
This is the code I use:
```dart
Stack(
                children: [
                  Container(
                    width: double.infinity,
                    height: MediaQuery.of(context).size.height -
                        (Platform().isWeb &&
                                getScreenSize(
                                        MediaQuery.of(context).size.width) ==
                                    ScreenSize.small
                            ? 5
                            : 100),
                    child: getContent,
                  ),
                  SlidingUpPanel(
                    controller: _panelController,
                    parallaxEnabled: true,
                    parallaxOffset: .1,
                    maxHeight: MediaQuery.of(context).size.height * 0.75,
                    minHeight: 30,
                    borderRadius: BorderRadius.only(
                      topLeft: Radius.circular(24),
                      topRight: Radius.circular(24),
                    ),
                    boxShadow: [
                      BoxShadow(
                        color: Colors.grey,
                        blurRadius: 5,
                        spreadRadius: 2,
                      ),
                    ],
                    panelSnapping: true,
                    backdropEnabled: true,
                    backdropTapClosesPanel: true,
                    panel: ExtraInformation(
                       ...
                    ),
                  ),
                ],
              )
```

**Closed** 2020-01-24 23:33 UTC
