### ISSUE TITLE
panelBuilder with WebView does not scroll correctly

### ISSUE THREAD

**Issue by fvisticot** [akshathjain/sliding_up_panel#118] opened 2020-03-30 20:28 UTC
The panelBuilder display a WebView (webview_flutter)
- Display is correct.
- I can scroll down the webview page
- When i scroll up, the panel starts to close

I do not see any ScrollController in the WebView package.

Any solution ? advice ?

I find a solution:
- I get the Webview Height when webview is finished (with JS)
- I redraw the view with the computed height

```
Widget _buildWebView(BuildContext context, ScrollController sc) {
    final height = MediaQuery.of(context).size.height;
    return SingleChildScrollView(
        controller: sc,
        child: ConstrainedBox(
            constraints: BoxConstraints(maxHeight: _maxHeight ?? height),
            child: GenericWebviewPage(
                onPageFinished: (double height) {
                  setState(() {
                    _maxHeight = height;
                  });
                },
                url: 'https://google.com')));
  }
```

**Comment by akshathjain** [comment] 2020-03-31 21:16
Duplicate of #90. Closing this issue. Please refer to that thread for updates.

**Closed by akshathjain** 2020-03-31 21:16 UTC
