### ISSUE TITLE
Parallax issue (reopen #116)

### ISSUE THREAD

**Issue by fvisticot** [akshathjain/sliding_up_panel#119] opened 2020-03-31 10:33 UTC
I have checked with the version 1.0.0 using panelController.
I confirm that the bug is still there (in my case).
When I drag up the panel for the first time, the panel start to slide and stops

For the click on the list elements it is OK with this version

**Comment by giga10** [comment] 2020-03-31 10:56
@fvisticot Latest version  is 1.0.1. It should be released today on pub.dev. Wait for that one.

**Comment by akshathjain** [comment] 2020-03-31 15:33
Duplicate of #116. Closing this issue and reopening the original.

**Closed by akshathjain** 2020-03-31 15:33 UTC
