### ISSUE TITLE
parallax

### ISSUE THREAD

**Issue by fvisticot** [akshathjain/sliding_up_panel#116] opened 2020-03-28 21:51 UTC
When using SlidingUpPanel with parallaxEnabled an parallaxOffset, sliding up and down with the panel is not fluid.
Sometime, the panel does not move when the finger scroll up and down.

In addition, when using parallax, listview elements (ListTile with onTap) from the panel are no more "Clickable"

Any advice ?

**Comment by akshathjain** [comment] 2020-03-30 22:37
This seems related to #94, which was recently just fixed. I'm going to go ahead and close this issue. Feel free to reopen it if the new version of the package doesn't resolve your issue.

**Comment by fvisticot** [comment] 2020-03-31 10:25
Tx for the update.
I have checked with the version 1.0.0 using panelController.
I confirm that the bug is still there (in my case).
When I drag up the panel for the first time, the panel start to slide and stops

For the click on the list elements it is OK with this version

**Comment by fvisticot** [comment] 2020-04-01 06:58
To give more information: the body is a basic GoogleMap widget without any stack inside
It seems the issue is the same as #68

**Comment by akshathjain** [comment] 2020-04-02 04:47
Closing this issue since its a duplicate of #68. Please follow that thread for updates.

**Closed by akshathjain** 2020-04-02 04:47 UTC
