### ISSUE TITLE
Ability to open/close the panel by sliding anywhere instead of dragging the top

### ISSUE THREAD

**Issue by GreyOakSoftware** [akshathjain/sliding_up_panel#99] opened 2020-01-31 17:05 UTC
Is there any way I could make the panel work as it normally does but instead of having to drag the top to open and close the panel, I can make it so that if I drag anywhere on the panel it first opens the panel then continues with scrolling?

**Comment by akshathjain** [comment] 2020-01-31 17:36
Yes, v1.0.0 introduced the `panelBuilder` property that allows you to achieve that functionality. Check out [this](https://pub.dev/packages/sliding_up_panel#adding-scrollable-elements-to-the-sliding-panel) sample for the specified behavior. 

Duplicate of  #17, #55, #60.

**Closed by akshathjain** 2020-01-31 17:36 UTC
